name: Trigger Test Repository Workflow

on: [push]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Test Repository Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Simeon-Zografov/test-repo/actions/workflows/test_execution.yaml/dispatches \
            -d '{"ref":"main"}'